version: '3.7'

services:
  db_test:
    container_name: db_test
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
    image: postgres:15
    hostname: db_test

# services:
#   db:
#     image: postgres:15
#     container_name: db_app
#     environment:
#       - POSTGRES_DB=test  
#       - POSTGRES_PASSWORD=password  
#       - POSTGRES_USER=root
    # ports:
    #   - "5432:5432"
    # command: -p 5432 
    # expose:
    #   - 5432
    # env_file:
    #   - .env-non-dev

  app:
    build: 
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db_test

  # celery:
  #   build: 
  #     context: .
  # flower