"""tochno update table user add superuser for all

Revision ID: 0a1c3eb987ab
Revises: f74025d22e6c
Create Date: 2023-04-15 21:46:57.823130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a1c3eb987ab'
down_revision = 'f74025d22e6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
