"""try make to get currency

Revision ID: 0c46fadea5ee
Revises: 3a394a9de1fd
Create Date: 2023-04-16 04:00:41.665699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c46fadea5ee'
down_revision = '3a394a9de1fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
