"""change timezone

Revision ID: 29504b46c52c
Revises: 76b395c03a6f
Create Date: 2023-04-25 21:39:44.264843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29504b46c52c'
down_revision = '76b395c03a6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('total_quantity_and_avg_price_instrument_account', 'instrument_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('total_quantity_and_avg_price_instrument_account', 'total_quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('total_quantity_and_avg_price_instrument_account', 'avg_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('total_quantity_and_avg_price_instrument_account', 'currency_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('total_quantity_and_avg_price_instrument_account', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('total_quantity_and_avg_price_instrument_account', 'instrument_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('total_quantity_and_avg_price_instrument_account', 'instrument_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('total_quantity_and_avg_price_instrument_account', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('total_quantity_and_avg_price_instrument_account', 'currency_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('total_quantity_and_avg_price_instrument_account', 'avg_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('total_quantity_and_avg_price_instrument_account', 'total_quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('total_quantity_and_avg_price_instrument_account', 'instrument_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
