"""add table total_quantity_and_avg_price_instrument_account

Revision ID: 76b395c03a6f
Revises: 50cd8ebfa262
Create Date: 2023-04-16 16:07:34.156748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76b395c03a6f'
down_revision = '50cd8ebfa262'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('total_quantity_and_avg_price_instrument_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_name', sa.String(), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('total_quantity_and_avg_price_instrument_account')
    # ### end Alembic commands ###
