"""add table instument_type

Revision ID: a1503105557b
Revises: 0a1c3eb987ab
Create Date: 2023-04-15 23:14:30.751733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1503105557b'
down_revision = '0a1c3eb987ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instument_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instument_type_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instument_type')
    # ### end Alembic commands ###
