"""change timezone3

Revision ID: a4b160745c57
Revises: b0f1e5af7033
Create Date: 2023-04-25 22:03:17.163052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4b160745c57'
down_revision = 'b0f1e5af7033'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
