"""2 try make to get currency

Revision ID: b005af722aab
Revises: 0c46fadea5ee
Create Date: 2023-04-16 04:13:38.796995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b005af722aab'
down_revision = '0c46fadea5ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
