"""change timezone2

Revision ID: b0f1e5af7033
Revises: 29504b46c52c
Create Date: 2023-04-25 21:56:03.392558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f1e5af7033'
down_revision = '29504b46c52c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
