"""change timezone4

Revision ID: b443408b0263
Revises: a4b160745c57
Create Date: 2023-04-25 22:08:56.384003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b443408b0263'
down_revision = 'a4b160745c57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
