"""update table user add superuser for all

Revision ID: f74025d22e6c
Revises: eab51d235d51
Create Date: 2023-04-15 21:43:18.779063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f74025d22e6c'
down_revision = 'eab51d235d51'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
