"""try 2 to add table operation_type

Revision ID: fad0f32e08c7
Revises: 911f3d8b3e0a
Create Date: 2023-04-16 11:03:53.792945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fad0f32e08c7'
down_revision = '911f3d8b3e0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instument', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('instument', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('instument', 'operation_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instument', 'operation_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('instument', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('instument', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
